# Site settings
title: Not Your Usual Tech Blog
description: Musings from an aspiring Data Scientist
baseurl: "/les-miller/" # the subpath of your site, e.g. /blog
url: "https://aromatic-toast.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lorem Ipsum
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: Lesley Miller
email: lesley.miller@alumni.ubc.ca
twitter_username: lorem_ipsum
github_username:  aromatic-toast
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
